spring.application.name=rideFlow
spring.datasource.url=jdbc:mysql://localhost:3306/rideflow_db?createTableifNotExists=true
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
